# Generated by Django 4.2.3 on 2023-07-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_posts_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="posts",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
