# Generated by Django 4.2.3 on 2023-07-26 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_posts_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="posts", options={"ordering": ["-post_date"]},
        ),
        migrations.AlterField(
            model_name="posts",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="blog.blogcategory"
            ),
        ),
        migrations.AlterField(
            model_name="posts",
            name="post_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("body", models.TextField()),
                ("comment_date", models.DateTimeField(auto_now_add=True)),
                ("active", models.BooleanField(default=False)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blog.posts"
                    ),
                ),
            ],
        ),
    ]
