# Generated by Django 4.2.3 on 2023-08-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_comment_post"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment", options={"ordering": ["-comment_date"]},
        ),
        migrations.AlterField(
            model_name="comment",
            name="body",
            field=models.TextField(verbose_name="Comment"),
        ),
    ]
