# Generated by Django 4.2.3 on 2023-07-23 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_profile_job_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="profile/ava3.webp", upload_to="profile/%y/%m/%d"
            ),
        ),
    ]
