# Generated by Django 4.2.3 on 2023-08-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_profile_city_alter_profile_job_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
