# Generated by Django 4.2.3 on 2023-07-17 18:02

from django.db import migrations, models
import job.models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0002_category_job_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="image",
            field=models.ImageField(default="", upload_to=job.models.image_upload),
            preserve_default=False,
        ),
    ]
