# Generated by Django 4.2.3 on 2023-07-18 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0003_job_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="max_salary",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
