# Generated by Django 4.2.3 on 2023-07-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0004_job_max_salary"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
