# Generated by Django 4.2.3 on 2023-07-18 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0006_apply"),
    ]

    operations = [
        migrations.AddField(
            model_name="apply",
            name="job_title",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="apply_job",
                to="job.job",
            ),
            preserve_default=False,
        ),
    ]
