# Generated by Django 4.2.3 on 2023-07-18 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0007_apply_job_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="apply",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
