# Generated by Django 4.2.3 on 2023-07-23 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0009_job_owner_alter_apply_cv"),
    ]

    operations = [
        migrations.RenameField(
            model_name="apply", old_name="name", new_name="first_name",
        ),
    ]
