# Generated by Django 4.2.3 on 2023-07-23 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0010_rename_name_apply_first_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apply",
            name="first_name",
            field=models.CharField(max_length=50, verbose_name="Name"),
        ),
    ]
