# Generated by Django 4.2.3 on 2023-07-24 16:16

from django.db import migrations, models
import job.models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0011_alter_apply_first_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="image",
            field=models.ImageField(
                default="profile/ava3.webp", upload_to=job.models.image_upload
            ),
        ),
    ]
