# Generated by Django 4.2.3 on 2023-08-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_job_qualifications_job_responsibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='benefits',
            field=models.TextField(blank=True, null=True),
        ),
    ]
